### ISSUE TITLE
Implement repetitive build jobs in a central place

### ISSUE THREAD

**Issue by kalinkrustev** [mojaloop/ci-config#38]

**Comment by kalinkrustev** [comment]
An example is the code added for `publish-prerelease` in https://github.com/mojaloop/central-services-stream/pull/141, but also many other jobs in the same .circleci/config.yml file

**Comment by kalinkrustev** [comment]
@elnyry-sam-k , what do you think of the idea of having the build jobs in a central place?

I prepared a draft orb here https://github.com/mojaloop/ci-config/pull/39, it is based on jobs taken from central-ledger with  added one more job for publishing the pre-release branches.

Repos can start reusing the jobs gradually unless they need something specific.

**Comment by elnyry-sam-k** [comment]
DRY, lets do it!!

Thanks for this, @kalinkrustev

**Comment by kalinkrustev** [comment]
@elnyry-sam-k actually putting multiple orbs in one repo is not a good idea, as the automation that Circle CI provides for publishing orbs is not convenient for such case. Can I create a new repo for the build orb? Maybe mojaloop/orb-build ?

**Comment by elnyry-sam-k** [comment]
ok, is something like `ci-config-orb-build` ok?

**Comment by kalinkrustev** [comment]
Moved to https://github.com/mojaloop/ci-config-orb-build/issues/1

@elnyry-sam-k, as per this [permissions matrix](https://circleci.com/docs/orb-author-intro/#permissions-matrix), I think I will need the mojaloop github org owner to create the orb `mojaloop/build` or to set the CIRCLE_TOKEN in this context https://app.circleci.com/settings/organization/github/mojaloop/contexts/1d64c5ff-d141-4bc2-9ccb-4c4ae3169041, so that orbs can be published automatically.

Currently I can't publish even a [dev](https://circleci.com/docs/orb-concepts/#development-orbs) release, as the orb `mojaloop/build` does not exist.

**Comment by elnyry-sam-k** [comment]
reached out on slack, lets sort it out
